language: python
dist: xenial
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  # pypandoc is needed only for submitting package to pypi
  - sed '/pypandoc/d' -i requirements.txt
  - pip install -U -r requirements.txt
  - ./setup.py install
script:
  - py.test --cov=ssh_ldap_pubkey --cov-report term -vv
  - pycodestyle
deploy:
  provider: pypi
  user: jirutka
  password:
    secure: "2tzmNOMTjVcyIckYun5iZbgr9/6nrhImD4eFYOCbFFDezilGmPHwfbgp0zx55nrkdNOSB/mgsV+pYAdq8+0CRd/BcZZb9oosyS7n1vjPAP9fMNa02SsaqTWDzDpcNnGbfg7qOhKC/FyQ+H4uXp8w+pe4RfJFCUS/ywOimBEYrSI="
  skip_cleanup: true
  on:
    tags: true
    python: 3.7
